# Generated by Django 4.1 on 2023-09-24 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidateResume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
